name: Build and Upload Video

on:
  workflow_dispatch:
    # Optional triggers
    # push:
    #   branches:
    #     - main
    # schedule:
    #   - cron: "0 0 * * *"  # Example: run daily at midnight UTC

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: node

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            node/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Build Video
        run: npm run build-video

      - name: Upload video artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-video
          path: output/video.mp4