name: Build and Upload Video

on:
  workflow_dispatch:
    # Optional triggers
    # push:
    #   branches:
    #     - main
    # schedule:
    #   - cron: "0 0 * * *"  # Example: run daily at midnight UTC

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('node/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: node

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Build Video
        run: npm run build-video
        working-directory: node

      - name: Upload video artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-video
          path: node/output/video.mp4