name: Secure Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write  # Docker push用

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          docker tag my-app:latest my-dockerhub-user/my-app:latest

      - name: Push Docker image
        run: |
          docker push my-dockerhub-user/my-app:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: build.log